apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  acme:
    # Email address used for ACME registration
    email: ${email}
    # The ACME server URL
    server: ${server}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      # name: letsencrypt-prod
      name: ${name}
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
